### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by gilberto85** [Mosi-Rivera/IsometricCheckersOnline#1]
demo is not working !!!!

**Comment by Mosi-Rivera** [comment]
I never deployed the App and had completely forgotten about it.
It should be up now.
Thanks for reminding me.

**Comment by gilberto85** [comment]
In ny end this demos is not working yet

**Comment by Mosi-Rivera** [comment]
I just tested and it is working. The following might be fixes to your issue:
      1. Open the app on two tabs to play with youself, it's not  a single player game.
      2. It might take a couple of seconds to load the app if the heroku app is sleeping.
      3. If you are told the page does not exist go into the developer tools network tab and disable cache then relead the page.

If none of this works it might be the browser, try using chrome.

**Comment by Mosi-Rivera** [comment]
.
